
services:
  db:
    image: postgres:17
    container_name: postgres_pdf
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
